export const personajes = [
    {
        nombre: "Joffrey Baratheon",
        familia: "Lannister",
        edad: 14,
        añosReinado: 2,
        img: "./img/joffrey.jpg",
        role: "rey",
    },
    {
        nombre: "Jaime Lannister",
        familia: "Lannister",
        edad: 34,
        img: "./img/jaime.jpg",
        arma: "Espada",
        destreza: 9,
        role: "luchador",
    },
    {
        nombre: "Daenerys Targaryen",
        familia: "Targaryen",
        edad: 16,
        img: "./img/daenerys.jpg",
        arma: "Espada",
        destreza: 7,
        role: "luchador",
    },
    {
        nombre: "Tyrion Lannister",
        familia: "Lannister",
        edad: 27,
        img: "./img/tyrion.jpg",
        asesora: "Daenerys Targaryen",
        role: "asesor",
    },
    {
        nombre: "Bronn",
        familia: "Stokeworth",
        edad: 27,
        img: "./img/bronn.jpg",
        escuda: "Jaime Lannister",
        pelotismo: 10,
        role: "escudero",
    },
];
